### ISSUE TITLE
@PutChild not work in mac Finder(bytes always 0)

### ISSUE THREAD

**Issue by zlp1992** [miltonio/milton2#101]
Hi, I'm using milton, and my upload code as follows:
`    @PutChild
    @Transactional
    public FileContentItem uploadFile(FolderContentItem parent, String name, byte[] bytes){
        String traceId = UuidGenUtil.createUuid();
        try {
            QUERY_LOGGER.info("[uploadFile][NetdiskController],action=Request, name={}, size={},traceId={}",name,bytes.length,traceId);`
In windows, i can upload file successfully, but with Mac Finder, the length of bytes is always 0, Anyone know why?

**Comment by bradmac** [comment]
Hiya. There is nothing wrong with that, thats just how Finder works

Finder is a very "chatty" client, instead of doing a single PUT it does a sequence of about 8 actions, which includes 2 or 3 PUT's of zero bytes.

Your application must correctly handle all of those individual requests or the upload as a whole will fail.

Many developers use some mechanism to keep the zero byte files out of their persistent store, such as holding a temporary in-memory representation of the file. But it is vital that the HTTP semantics of each operation are correct.

**Comment by zlp1992** [comment]
Get it, Thanks

**Comment by jiangzuowei-dev** [comment]
> Hiya. There is nothing wrong with that, thats just how Finder works
> 
> Finder is a very "chatty" client, instead of doing a single PUT it does a sequence of about 8 actions, which includes 2 or 3 PUT's of zero bytes.
> 
> Your application must correctly handle all of those individual requests or the upload as a whole will fail.
> 
> Many developers use some mechanism to keep the zero byte files out of their persistent store, such as holding a temporary in-memory representation of the file. But it is vital that the HTTP semantics of each operation are correct.

Hello teacher, I only had 3 zero byte PUT when uploading, and that's it. The console didn't output any error messages. How can I troubleshoot
