### ISSUE TITLE
Etag delay

### ISSUE THREAD

**Issue by ysyelite** [miltonio/milton2#52]
At first, i implemented @modifiedDate and @UniqueId

when i changed schedule, check modifiedDate.
![before](https://cloud.githubusercontent.com/assets/9716259/7405255/1df30f48-ef2b-11e4-969f-e2e3257b7f61.jpg)
they show last modifieddate is 11:11:05.
And after changed i Also updatedate and return them to handler.
![afterupdate](https://cloud.githubusercontent.com/assets/9716259/7405267/5e7c0844-ef2b-11e4-9002-2d8ba5158df1.jpg)
![andreturn](https://cloud.githubusercontent.com/assets/9716259/7405270/61a5e5b2-ef2b-11e4-8e1e-29bb5bafc4a7.JPG)
modifiedDate is changed to 11:14:14.
But, after update when check modifiedDate it wasn't changed.
![afterfind](https://cloud.githubusercontent.com/assets/9716259/7405298/c4110614-ef2b-11e4-977f-4597a44169c5.jpg)

So, i've got same Etag after Update.
![sameetag](https://cloud.githubusercontent.com/assets/9716259/7405303/dec5b19e-ef2b-11e4-91e0-3e57ff6001e5.jpg)
Hope to know solve this problem.

**Comment by dachristensen** [comment]
I ran into this problem as well. I believe that the issue is that the 'replace' method of the PutChildAnnotationHandler returns void... or in other word it simply throws away the return value from your @PutChild method. This means that AnnoFileResource which implements ReplaceableResource does not update it's source object after calling this method. This in turn means that when it later goes to calculate the ETag that it is using the original source object that it used to build the AnnoFileResource and not the version of the object that you returned from your @PutChild.



You can solve this problem by mutating the state of the object passed into the @PutChild method rather than returning a new one (i.e. call setModifiedDate()). Personally, I prefer to have my data objects be immutable, so this didn't work very well for my architecture. I played around with patching Milton to update the source object in AnnFileResource but in the end, I ditched the annotation based framework and implemented the various resource interfaces myself for greater flexibility.





Daniel L. Christensen

Software Engineer

Novell, Inc.




>>> ysyelite <notifications@github.com> 4/29/2015 8:27 PM >>>

 
At first, i implemented @modifiedDate and @UniqueId

when i changed schedule, check modifiedDate.

 they show last modifieddate is 11:11:05.
 And after changed i Also updatedate and return them to handler.


 modifiedDate is changed to 11:14:14.
 But, after update when check modifiedDate it wasn't changed.


So, i've got same Etag after Update.

 Hope to know solve this problem.

-
